### ISSUE TITLE
Incorrect RAM values

### ISSUE THREAD

**Issue by gerrydoro** [Sonelli/juicessh-performancemonitor#18]
Hi everybody!
I started to use this plugin recently and immediately I found this bug:
The "Free RAM" counter displays the value "1GB" when my server had ~1.7GB of available memory

Screenshots:
http://postimg.org/image/s96z5dfbj/
http://postimg.org/image/une6hyp9d/

Thank you for your attention

**Comment by dougsimmons** [comment]
Same for me too, on Debian, 240MB out of 8GB used, the app shows 5GB, here's /proc/meminfo:

root@302:~# cat /proc/meminfo
MemTotal:        8197724 kB
MemFree:          247124 kB
MemAvailable:    5201088 kB
Buffers:          240788 kB
Cached:          4992004 kB
SwapCached:        17284 kB
Active:          4829968 kB
Inactive:        2695156 kB
Active(anon):    2162032 kB
Inactive(anon):   423208 kB
Active(file):    2667936 kB
Inactive(file):  2271948 kB
Unevictable:        9672 kB
Mlocked:            9868 kB
SwapTotal:       4305384 kB
SwapFree:        3900048 kB
Dirty:              4184 kB
Writeback:             0 kB
AnonPages:       2290532 kB
Mapped:           130660 kB
Shmem:            289444 kB
Slab:             334408 kB
SReclaimable:     267496 kB
SUnreclaim:        66912 kB
KernelStack:        5360 kB
PageTables:        23728 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8404244 kB
Committed_AS:    3137808 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      152116 kB
VmallocChunk:   34359486180 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      118720 kB
DirectMap2M:     8269824 kB

It is otherwise highly badass. Thanks.
Doug

**Comment by mxdpeep** [comment]
Doug, it shows correct numbers, you have 5 GB RAM as cache - Linux does it all the time, cache and buffers
