### ISSUE TITLE
Not able to see juice servers in plugin

### ISSUE THREAD

**Issue by geraldsweers** [Sonelli/juicessh-performancemonitor#71]
No servers from juicessh in list its empty. Might have to do with a update from juicessh today

**Comment by Longshot** [comment]
Same problem here.
The servers dont show up anymore in the list.
Ive deleted and reinstalled the plugin but it didnt help.

**Comment by jamese641** [comment]
Here's a quote from an email I got:

We have a fix for this, however it's taking Google a long time to approve
play store updates at the moment due to COVID.

You can download v3.1.2-beta2 directly from our website:
https://juicessh.com/changelog

This beta build includes the fix.

Apologies for the inconvenience

Paul

**Comment by PaulMaddox** [comment]
Resolved in the latest versions of JuiceSSH
